simple_test_project01/simple_test_root/Genres/urls.py
from django.urls import path
from . import views
from .views import ArtistDetailView

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('', views.Genres.as_view(), name='Genres'),
    path('contact/', views.contact, name='contact'),
    path('rap/', views.Rap.as_view(), name='rap'),
    path('pop/', views.Pop.as_view(), name='pop'),
    path('country/', views.Country.as_view(), name='country'),
    path('artist/<int:pk>/', ArtistDetailView.as_view(), name='ArtistDetail'),
    path('userprofiles/', views.UserProfileList.as_view(), name='userprofile_list'),
    path("userprofile/create/", views.UserProfileCreate.as_view(), name="userprofile_create"),
    path("userprofile/<int:pk>/", views.UserProfileDetail.as_view(), name="userprofile_detail"),
    path("userprofile/update/<int:pk>/", views.UserProfileUpdate.as_view(), name="userprofile_update"),
    path("userprofile/delete/<int:pk>/", views.UserProfileDelete.as_view(), name="userprofile_delete"),
]

simple_test_project01/simple_test_root/Users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<str:pagename>/', views.index, name='index'),
    path('', views.index, name='index'),
]

simple_test_project01/simple_test_root/simple_test_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Genres/', include('Genres.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_test_project01/simple_test_root/Genres/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Artist(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    youtube_video_id = models.CharField(max_length=100, null=True) 

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ArtistDetail', kwargs={'pk':self.pk})


class YouTubeLink(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    link = models.URLField()

    def __str__(self):
        return self.title
    
    def video_id(self):
        # Extract video ID from YouTube URL
        url_parts = self.link.split("?v=")
        if len(url_parts) > 1:
            return url_parts[1]
        else:
            # If the URL format is different, you may need to handle it differently
            return None
    
class UserProfile(models.Model):
    user_name = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_pic = models.ImageField(upload_to='users/', null=True, blank=True)

    def __str__(self):
        return self.user_name
    
    def get_absolute_url(self):
        return reverse('UserProfileDetail', kwargs={'pk':self.pk})

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    artist = models.ForeignKey(Artist, on_delete=models.SET_NULL, null=True, related_name='orders')

    def __str__(self):
        return f'Order {self.pk} by {self.user.username}'

    def get_absolute_url(self):
        return reverse('order_detail', kwargs={'pk': self.pk})

simple_test_project01/simple_test_root/Genres/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User 
from .models import Order

class OrderForm(ModelForm):
    class Meta:
        model = Order 
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

simple_test_project01/simple_test_root/Genres/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Genre, Artist, UserProfile
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, get_connection
from .contact import ContactForm
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .forms import OrderForm, CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


#from .filters import OrderFilter

def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was create for ' + user)
            return redirect('login')
    context = {'form':form}
    return render(request, 'genres/register.html', context)

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('Genres')
        else:
            messages.info(request, 'Username OR Password is incorrect')
            
    context = {}
    return render(request, 'genres/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('login')

class Genres(ListView):
    template_name = 'Genres/home.html'
    queryset = Genre.objects.all()
    context_object_name = 'genres'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['attractions'] = Artist.objects.all()
        return context
    
def contact(request):
	submitted = False
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			con = get_connection('django.core.mail.backends.console.EmailBackend')
			send_mail(
				cd['subject'],
				cd['message'],
				cd.get('email', 'noreply@dcu.ie'),
				['student@dcu.ie'], # change this
				connection=con
			)
			return HttpResponseRedirect('/contact?submitted=True')
	else:
		form = ContactForm()
		if 'submitted' in request.GET:
			submitted = True
	context = {
		'form': form,
		'page_list': Genre.objects.all(),
		'submitted': submitted
	}
	return render(request, 'User/contact.html', context)

class Rap(ListView):
    template_name = 'genres/rap.html'
    queryset = Genre.objects.all()
    context_object_name = 'Genres'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        genre = Genre.objects.get(name='Rap')
        context['genre'] = genre
        context['artists'] = Artist.objects.filter(genre=genre)
        return context

class Pop(ListView):
    template_name = 'genres/pop.html'
    queryset = Genre.objects.all()
    context_object_name = 'Genres'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        genre = Genre.objects.get(name='Pop')
        context['genre'] = genre
        context['artists'] = Artist.objects.filter(genre=genre)
        return context

class Country(ListView):
    template_name = 'genres/country.html'
    queryset = Genre.objects.all()
    context_object_name = 'Genres'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        genre = Genre.objects.get(name='Country')
        context['genre'] = genre
        context['artists'] = Artist.objects.filter(genre=genre)
        return context
    
class ArtistDetailView(DetailView):
    model = Artist
    template_name = 'genres/artist_detail.html'

class UserProfileUpdate(UpdateView):
    model = UserProfile
    template_name = "genres/userprofile_update_form.html"
    fields = ["bio", "profile_pic"]

class UserProfileDelete(DeleteView):
    model = UserProfile
    template_name = "genres/userprofile_delete_form.html"
    success_url = reverse_lazy("userprofile_list")

class UserProfileCreate(CreateView):
    model = UserProfile
    template_name = 'genres/userprofile_create_form.html'
    fields = ["bio", "profile_pic"]

class UserProfileDetail(DetailView):
    model = UserProfile
    template_name = 'genres/userprofile_detail.html'

class UserProfileList(ListView):
    model = UserProfile
    template_name = 'genres/userprofile_list.html'

simple_test_project01/simple_test_root/Genres/templates/genres/artist_detail.html
{% extends "base.html" %}

{% block title %}
    {{ artist.name }}
{% endblock %}
{% block content %}
    <h1>{{ artist.name }}</h1>
    <p>Genre: {{ artist.genre }}</p>
    
    {% for youtube_link in artist.youtubelink_set.all %}
        <h2>{{ youtube_link.title }}</h2>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ youtube_video_id }}" frameborder="0" allowfullscreen></iframe>
    {% endfor %}
{% endblock %}

simple_test_project01/simple_test_root/Genres/templates/genres/contact.html
{% extends "base.html" %}
{% block title %}Contact Us{% endblock title %}
{% block main_content %}
	<h1>Contact us</h1>
	{% if submitted %}
		<p class="success">
		Your message was submitted successfully. Thank you.
		</p>

	{% else %}
		<form action="" method="post" novalidate>
		<table>
			{{ form.as_table }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit"></td>
			</tr>
		</table>
		{% csrf_token %}
		</form>
	{% endif %}
{% endblock main_content %}

simple_test_project01/simple_test_root/Genres/templates/genres/country.html
{% extends "base.html" %}

{% block title %}
    Country
{% endblock %}

{% block content %}
    <h1>Country Genre</h1>
    <p>This is the page for Country music.</p>

    <h2> Country Artists:</h2>
    <ul>
        {% for artist in artists %}
            <li><a href="{% url 'ArtistDetail' pk=artist.pk %}">{{ artist.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

simple_test_project01/simple_test_root/Genres/templates/genres/home.html
{% extends "base.html" %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
{% endblock %}

simple_test_project01/simple_test_root/Genres/templates/genres/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

simple_test_project01/simple_test_root/Genres/templates/genres/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <!-- Optional: Include Bootstrap or other CSS frameworks if you need styling -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <!-- Display the current user's username if they are logged in -->
        {% if request.user.is_authenticated %}
            <p>Hello, {{ request.user.username }}!</p>
            <a href="{% url 'logout' %}" class="btn btn-primary">Logout</a>
        {% else %}
            <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
            <a href="{% url 'register' %}" class="btn btn-primary">Register</a>
        {% endif %}
    </div>
</body>
</html>

simple_test_project01/simple_test_root/Genres/templates/genres/pop.html
{% extends "base.html" %}

{% block title %}
    Pop
{% endblock %}

{% block content %}
    <h1>Pop Genre</h1>
    <p>This is the page for Pop music.</p>

    <h2>Pop Artists:</h2>
    <ul>
        {% for artist in artists %}
            <li><a href="{% url 'ArtistDetail' pk=artist.pk %}">{{ artist.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

simple_test_project01/simple_test_root/Genres/templates/genres/rap.html
{% extends "base.html" %}

{% block title %}
    Rap
{% endblock %}

{% block content %}
    <h1>Rap Genre</h1>
    <p>This is the page for rap music.</p>

    <h2>Rap Artists:</h2>
    <ul>
        {% for artist in artists %}
            <li><a href="{% url 'ArtistDetail' pk=artist.pk %}">{{ artist.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

simple_test_project01/simple_test_root/Genres/templates/genres/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

                {{form.errors}}
                
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username...';
		form_fields[2].placeholder='Email...';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

simple_test_project01/simple_test_root/Genres/templates/genres/userprofile_create_form.html
<h2>Create User Profile</h2>
<form method="post">
<div>
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Submit" />
</div>
</form>

simple_test_project01/simple_test_root/Genres/templates/genres/userprofile_delete_form.html
<h2>Delete User Profile</h2>
<form method="post">
<div>
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ user.user_name }}"?</p>
  <input type="submit" value="Confirm" />
</div>

simple_test_project01/simple_test_root/Genres/templates/genres/userprofile_detail.html
<h2>User Profile</h2>
<p>Username: {{ profile.user_name }}</p>
<p>Bio: {{ profile.bio }}</p>

simple_test_project01/simple_test_root/Genres/templates/genres/userprofile_list.html
<h3>User Profiles</h3>
<ul>
{% for user in user_list %}
    <li>{{ user.user_name }} ({{user.user_type}})</li>
{% endfor %}
</ul>

simple_test_project01/simple_test_root/Genres/templates/genres/userprofile_update_form.html
<h2>Update User Profile</h2>
<form method="post">
<div>
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Submit" />
</div>
</form>